---
id: pgconf-asia-2016
base_name: pgroonga
tags:
- rabbit
- pgroonga
- postgresql
presentation_date: 2016-12-03
version: 2016.12.3.0
licenses:
- CC-BY-SA-4.0
- CC-BY-3.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
